openapi: "3.1.0"
info:
  title: FakeStore API
  version: "1.0.0"
servers:
- url: http://localhost:3004/v1
  description: Fake Store API Dev Server 
security: []
paths: 
  /plants:
    description: All the plants
    get:
      summary: List all plants
      operationId: getAllPlants
      description: List all the plants available
      responses:
        "200":
          description: All the plants
        "400":
          description: Bad Request.
          
  /customers:
    description: All the registered customers
    get:
      summary: List all customers
      operationId: getAllCustomers
      description: List all the registered customers
      responses:
        "200":
          description: All the customers
        "400":
          description: Bad Request.

  /customers/{username}:
    get:
      summary: Get customer by username
      operationId: getCustomerByUsername
      description: Get a customer by their username
      parameters:
        - in: path
          name: username
          description: The username of the customer
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer found
        '401':
          description: Customer not found
        '400':
          description: Bad Request.

